backend:
  name: github
  repo: markloweai/victor-hugo
  branch: master
  
media_folder: media_folder

collections:
  - name: post
    label: Post
    folder: site/content/post
    create: true
    fields:
      - {name: title, label: Title}
      - {name: body, label: Body, widget: markdown}
